hyperparameters:
  epochs: 50
  batch_size: 7
  learning_rate: 0.001
  sample_rate: 32000
  number_of_samples: 1

paths:
  output_dir: "/workspaces/underwater/dev/underwater_snd/test/mel_nadam_snd"

dataset:
  type: "deepership"
  train_metadata: "/workspaces/underwater/dataset/07_classified_wav_files/inclusion_2000_exclusion_4000/metadata/filtered/filtered_metadata_1s_train_oversampled.csv"
  validation_metadata: "/workspaces/underwater/dataset/07_classified_wav_files/inclusion_2000_exclusion_4000/metadata/filtered/filtered_metadata_1s_validation.csv"
  test_metadata: "/workspaces/underwater/dataset/07_classified_wav_files/inclusion_2000_exclusion_4000/metadata/filtered/filtered_metadata_1s_test.csv"

preprocessing:
  type: "mel"
