hyperparameters:
  epochs: 50
  batch_size: 7
  learning_rate: 0.001
  sample_rate: 32000
  number_of_samples: 1

paths:
  output_dir: "/workspaces/underwater/dev/training/inc4000_50epochs_oversampled_sgd"
  train_metadata: "/workspaces/underwater/dataset/07_classified_wav_files/inclusion_4000_exclusion_6000/metadata/filtered/filtered_metadata_1s_train_oversampled.csv"
  validation_metadata: "/workspaces/underwater/dataset/07_classified_wav_files/inclusion_3000_exclusion_5000/metadata/filtered/filtered_metadata_1s_validation.csv"

preprocessing:
  type: "mel"
