hyperparameters:
  epochs: 50
  batch_size: 25
  learning_rate: 0.001
  lr_schd_gamma: 0.9

optim:
  type: "sgd"
  early_stop: 0

model:
  name: "resnet18"
  cnn_depth: 4
  num_of_classes: 4
  input_channels: 3

paths:
  output_dir: "/workspaces/underwater/dev/underwater_snd/out/inc2000_resnet_sgd_b25_noback"

dataset:
  type: "deepershipfeature"
  train_root_path: "/workspaces/underwater/dataset/DeeperShip/2k/preprocessed/train/"
  validation_root_path: "/workspaces/underwater/dataset/DeeperShip/2k/preprocessed/validation/"
  test_root_path: "/workspaces/underwater/dataset/DeeperShip/2k/preprocessed/test/"
